name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]

env:
  TF_DIRECTORY: ./terraform

permissions:
  id-token: write
  contents: read

jobs:
  aws-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: "arn:aws:iam::075006646450:role/OICD-github-actions"
          aws-region: "eu-west-1"
      - name: Additional steps
        run: |
          # Your commands that require AWS credentials
          aws sts get-caller-identity
  terraform:
    runs-on: ubuntu-latest
    needs: aws-credentials
    defaults:
      run:
        working-directory: ${{ env.TF_DIRECTORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check OICD token
        run: |
          echo $ACTIONS_ID_TOKEN_REQUEST_URL
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.0"
      
      - name: Terraform Init
        run: terraform init -backend-config=dev.config

      - name: Terraform Validate
        run: terraform validate
